// 语言配置
const translations = {
    'zh-CN': {
        'settings.title': '设置',
        'settings.theme': '主题',
        'settings.time': '时间显示',
        'settings.time.24h': '24小时制',
        'settings.time.seconds': '显示秒数',
        'settings.time.blink': '分隔符闪烁',
        'settings.navigation': '导航设置',
        'settings.navigation.reset': '重置快捷方式',
        'settings.language': '语言',
        'settings.background': '背景透明度',
        'settings.background.opacity': '透明度',
        'settings.background.opacity.0': '0%',
        'settings.background.opacity.10': '10%',
        'settings.background.opacity.20': '20%',
        'settings.background.opacity.30': '30%',
        'settings.shortcut.newtab': '新标签页打开快捷方式',
        'settings.shortcut.newtab.desc': '开启后，点击快捷方式将在新标签页打开，否则在本页面跳转',
        'settings.theme.default': '默认主题',
        'settings.theme.custom': '自定义主题',
        'settings.theme.add-custom': '添加自定义主题',
        'settings.theme.custom.title': '自定义主题',
        'settings.theme.custom.name': '主题名称',
        'settings.theme.custom.preview': '预览效果',
        'settings.theme.custom.save': '保存',
        'settings.theme.custom.cancel': '取消',
        'settings.theme.custom.delete.title': '删除主题',
        'settings.theme.custom.delete.confirm': '确定要删除这个自定义主题吗？此操作无法撤销。',
        'settings.theme.custom.delete.cancel': '取消',
        'settings.custom-theme.primary': '主色调',
        'settings.custom-theme.gradient1': '渐变色1',
        'settings.custom-theme.gradient2': '渐变色2',
        'settings.custom-theme.gradient3': '渐变色3',
        'settings.custom-theme.gradient4': '渐变色4',
        'settings.custom-theme.gradient5': '渐变色5',
        'search.placeholder': '请输入搜索内容...',
        'search.engines.google': 'Google',
        'search.engines.bing': 'Bing',
        'search.engines.baidu': '百度',
        'search.engines.bingcn': '必应中国',
        'search.engines.github': 'GitHub',
        'search.engines.zhihu': '知乎',
        'shortcut.add': '添加快捷方式',
        'shortcut.add.title': '添加网站捷径',
        'shortcut.add.url': '网址',
        'shortcut.add.name': '标题',
        'shortcut.add.auto': '- 留空即自动获取',
        'shortcut.add.cancel': '取消',
        'shortcut.add.confirm': '添加',
        'shortcut.reset.title': '确认重置',
        'shortcut.reset.message': '确定要重置所有快捷方式吗？这将删除所有自定义的快捷方式。',
        'shortcut.reset.cancel': '取消',
        'shortcut.reset.confirm': '确定重置',
        'shortcut.delete.title': '确认删除',
        'shortcut.delete.message': '确定要删除这个快捷方式吗？',
        'shortcut.delete.cancel': '取消',
        'shortcut.delete.confirm': '确定删除',
        'theme.pink': '粉色',
        'theme.deep-ocean': '深海',
        'theme.forest': '森林',
        'theme.sunset': '日落',
        'theme.neon': '霓虹',
        'theme.royal': '皇家',
        'theme.desert': '沙漠',
        'theme.aurora': '极光',
        'theme.cherry': '樱花',
        'theme.emerald': '翡翠',
        'theme.dark-night': '暗夜',
        'theme.pure-white': '纯白',
        'theme.cyberpunk': '赛博朋克',
        'theme.pastel': '柔和',
        'theme.midnight': '午夜',
        'theme.lavender': '薰衣草',
        'theme.ocean': '海洋',
        'theme.autumn': '秋季',
        'theme.mint': '薄荷',
        'theme.galaxy': '银河',
        'theme.black-yellow': '黑金',
        'theme.blue-yellow': '蓝金',
        'theme.orange-red': '橙红',
        'theme.black-blue': '黑蓝',
        'theme.purple-gold': '紫金',
        'theme.emerald-gold': '翠金',
        'theme.ruby-silver': '红银',
        'theme.jade-purple': '翠紫',
        'theme.crimson-gold': '绯金',
        'theme.azure-rose': '蓝粉',
        'theme.custom': '自定义',
        'settings.theme.custom.preset': '预设配色',
        'settings.theme.custom.preset.title': '选择预设配色',
        'settings.theme.custom.preset.use': '使用此配色',
        'settings.theme.custom.preset.custom': '自定义配色',
        'settings.theme.custom.preset.emerald-gold': '翠金配色',
        'settings.theme.custom.preset.desc.emerald-gold': '青翠欲滴的翡翠绿与璀璨夺目的金色完美融合',
        'settings.theme.custom.preset.ocean-sunset': '海洋晚霞',
        'settings.theme.custom.preset.desc.ocean-sunset': '深邃的海蓝与温暖的落日金光交相辉映',
        'settings.theme.custom.preset.forest-dawn': '森林晨光',
        'settings.theme.custom.preset.desc.forest-dawn': '清新的森林绿与温柔的晨曦金光相互交织',
        'settings.theme.custom.preset.desert-oasis': '沙漠绿洲',
        'settings.theme.custom.preset.desc.desert-oasis': '金色沙漠与绿洲碧水的完美结合'
    },
    'en-US': {
        'settings.title': 'Settings',
        'settings.theme': 'Theme',
        'settings.time': 'Time Display',
        'settings.time.24h': '24-hour Format',
        'settings.time.seconds': 'Show Seconds',
        'settings.time.blink': 'Blink Separator',
        'settings.navigation': 'Navigation Settings',
        'settings.navigation.reset': 'Reset Shortcuts',
        'settings.language': 'Language',
        'settings.background': 'Background Opacity',
        'settings.background.opacity': 'Opacity',
        'settings.background.opacity.0': '0%',
        'settings.background.opacity.10': '10%',
        'settings.background.opacity.20': '20%',
        'settings.background.opacity.30': '30%',
        'settings.shortcut.newtab': 'Open shortcuts in new tab',
        'settings.shortcut.newtab.desc': 'If enabled, shortcuts open in a new tab; otherwise, open in the current page',
        'settings.theme.default': 'Default Themes',
        'settings.theme.custom': 'Custom Themes',
        'settings.theme.add-custom': 'Add Custom Theme',
        'settings.theme.custom.title': 'Custom Theme',
        'settings.theme.custom.name': 'Theme Name',
        'settings.theme.custom.preview': 'Preview',
        'settings.theme.custom.save': 'Save',
        'settings.theme.custom.cancel': 'Cancel',
        'settings.theme.custom.delete.title': 'Delete Theme',
        'settings.theme.custom.delete.confirm': 'Are you sure you want to delete this custom theme? This action cannot be undone.',
        'settings.theme.custom.delete.cancel': 'Cancel',
        'settings.custom-theme.primary': 'Primary Color',
        'settings.custom-theme.gradient1': 'Gradient Color 1',
        'settings.custom-theme.gradient2': 'Gradient Color 2',
        'settings.custom-theme.gradient3': 'Gradient Color 3',
        'settings.custom-theme.gradient4': 'Gradient Color 4',
        'settings.custom-theme.gradient5': 'Gradient Color 5',
        'search.placeholder': 'Enter search terms...',
        'search.engines.google': 'Google',
        'search.engines.bing': 'Bing',
        'search.engines.baidu': 'Baidu',
        'search.engines.bingcn': 'Bing China',
        'search.engines.github': 'GitHub',
        'search.engines.zhihu': 'Zhihu',
        'shortcut.add': 'Add Shortcut',
        'shortcut.add.title': 'Add Website Shortcut',
        'shortcut.add.url': 'URL',
        'shortcut.add.name': 'Title',
        'shortcut.add.auto': '- Auto-fetch if empty',
        'shortcut.add.cancel': 'Cancel',
        'shortcut.add.confirm': 'Add',
        'shortcut.reset.title': 'Confirm Reset',
        'shortcut.reset.message': 'Are you sure you want to reset all shortcuts? This will delete all custom shortcuts.',
        'shortcut.reset.cancel': 'Cancel',
        'shortcut.reset.confirm': 'Reset',
        'shortcut.delete.title': 'Confirm Delete',
        'shortcut.delete.message': 'Are you sure you want to delete this shortcut?',
        'shortcut.delete.cancel': 'Cancel',
        'shortcut.delete.confirm': 'Delete',
        'theme.pink': 'Pink',
        'theme.deep-ocean': 'Deep Ocean',
        'theme.forest': 'Forest',
        'theme.sunset': 'Sunset',
        'theme.neon': 'Neon',
        'theme.royal': 'Royal',
        'theme.desert': 'Desert',
        'theme.aurora': 'Aurora',
        'theme.cherry': 'Cherry',
        'theme.emerald': 'Emerald',
        'theme.dark-night': 'Dark Night',
        'theme.pure-white': 'Pure White',
        'theme.cyberpunk': 'Cyberpunk',
        'theme.pastel': 'Pastel',
        'theme.midnight': 'Midnight',
        'theme.lavender': 'Lavender',
        'theme.ocean': 'Ocean',
        'theme.autumn': 'Autumn',
        'theme.mint': 'Mint',
        'theme.galaxy': 'Galaxy',
        'theme.black-yellow': 'Black Gold',
        'theme.blue-yellow': 'Blue Gold',
        'theme.orange-red': 'Orange Red',
        'theme.black-blue': 'Black Blue',
        'theme.purple-gold': 'Purple Gold',
        'theme.emerald-gold': 'Emerald Gold',
        'theme.ruby-silver': 'Ruby Silver',
        'theme.jade-purple': 'Jade Purple',
        'theme.crimson-gold': 'Crimson Gold',
        'theme.azure-rose': 'Azure Rose',
        'theme.custom': 'Custom',
        'settings.theme.custom.preset': 'Preset Colors',
        'settings.theme.custom.preset.title': 'Choose Preset Colors',
        'settings.theme.custom.preset.use': 'Use This Color Scheme',
        'settings.theme.custom.preset.custom': 'Custom Colors',
        'settings.theme.custom.preset.emerald-gold': 'Emerald Gold',
        'settings.theme.custom.preset.desc.emerald-gold': 'Perfect blend of lush emerald green and dazzling gold',
        'settings.theme.custom.preset.ocean-sunset': 'Ocean Sunset',
        'settings.theme.custom.preset.desc.ocean-sunset': 'Deep ocean blue meets warm sunset gold',
        'settings.theme.custom.preset.forest-dawn': 'Forest Dawn',
        'settings.theme.custom.preset.desc.forest-dawn': 'Fresh forest green intertwined with gentle dawn gold',
        'settings.theme.custom.preset.desert-oasis': 'Desert Oasis',
        'settings.theme.custom.preset.desc.desert-oasis': 'Perfect harmony of golden desert and oasis waters'
    }
};

export class LanguageManager {
    constructor() {
        this.currentLang = localStorage.getItem('preferred_language') || 'zh-CN';
        this.translations = translations;
    }

    // 切换语言
    setLanguage(lang) {
        if (this.translations[lang]) {
            this.currentLang = lang;
            localStorage.setItem('preferred_language', lang);
            this.updatePageTranslations();
        }
    }

    // 获取当前语言的翻译
    getTranslation(key) {
        return this.translations[this.currentLang][key] || key;
    }

    // 更新页面上所有需要翻译的元素
    updatePageTranslations() {
        const elements = document.querySelectorAll('[data-i18n]');
        elements.forEach(element => {
            const key = element.getAttribute('data-i18n');
            const translation = this.getTranslation(key);
            
            if (element.tagName === 'INPUT' && element.getAttribute('placeholder')) {
                element.placeholder = translation;
            } else {
                element.textContent = translation;
            }
        });
    }
} 